// GENERATED BY `json2dart --name Accounts --from accounts.json`

/// {@tool json2dart --name Accounts}
/// * items: `<AccountItem>[]`
/// * summary: `AccountSummary()`
/// * months: `<String, AccMonthItem>{"2020-08":{}}`
/// * count: `1`
/// {@end-tool}
class Accounts {
  List<AccountItem> items;
  AccountSummary summary;
  Map<String, AccMonthItem> months;
  num count;

  Accounts({
    this.items,
    this.summary,
    this.months,
    this.count,
  });

  Accounts.fromJson(Map<String, dynamic> json) {
    items =
        (json["items"] as List)?.map((v) => AccountItem.fromJson(v))?.toList();
    summary = json["summary"] != null
        ? AccountSummary.fromJson(json["summary"])
        : null;
    months = (json["months"] as Map)
        ?.map((k, v) => MapEntry(k, AccMonthItem.fromJson(v)));
    count = json["count"] as num;
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (items != null) {
      json["items"] = items.map((v) => v.toJson()).toList();
    }
    if (summary != null) {
      json["summary"] = summary.toJson();
    }
    if (months != null) {
      json["months"] = months.map((k, v) => MapEntry(k, v.toJson()));
    }
    json["count"] = count;
    return json;
  }
}

/// {@tool json2dart --name AccountItem}
/// * id: `1`
/// * accName(acc_name): `"name"`
/// * totalBalance: `38.9`
/// * details: `<AccountDetailItem>[]`
/// {@end-tool}
class AccountItem {
  num id;
  String accName;
  num totalBalance;
  List<AccountDetailItem> details;

  AccountItem({
    this.id,
    this.accName,
    this.totalBalance,
    this.details,
  });

  AccountItem.fromJson(Map<String, dynamic> json) {
    id = json["id"] as num;
    accName = json["acc_name"] as String;
    totalBalance = json["totalBalance"] as num;
    details = (json["details"] as List)
        ?.map((v) => AccountDetailItem.fromJson(v))
        ?.toList();
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    json["id"] = id;
    json["acc_name"] = accName;
    json["totalBalance"] = totalBalance;
    if (details != null) {
      json["details"] = details.map((v) => v.toJson()).toList();
    }
    return json;
  }
}

/// {@tool json2dart --name AccountDetailItem}
/// * id: `11`
/// * amount: `10.1`
/// * remark: `"add"`
/// {@end-tool}
class AccountDetailItem {
  num id;
  num amount;
  String remark;

  AccountDetailItem({
    this.id,
    this.amount,
    this.remark,
  });

  AccountDetailItem.fromJson(Map<String, dynamic> json) {
    id = json["id"] as num;
    amount = json["amount"] as num;
    remark = json["remark"] as String;
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    json["id"] = id;
    json["amount"] = amount;
    json["remark"] = remark;
    return json;
  }
}

/// {@tool json2dart --name AccountSummary}
/// * blance: `38.9`
/// * users: `1`
/// * json: `AccountSummaryJson()`
/// {@end-tool}
class AccountSummary {
  num blance;
  num users;
  AccountSummaryJson json;

  AccountSummary({
    this.blance,
    this.users,
    this.json,
  });

  AccountSummary.fromJson(Map<String, dynamic> j) {
    blance = j["blance"] as num;
    users = j["users"] as num;
    json = j["json"] != null ? AccountSummaryJson.fromJson(j["json"]) : null;
  }

  Map<String, dynamic> toJson() {
    final j = <String, dynamic>{};
    j["blance"] = blance;
    j["users"] = users;
    if (json != null) {
      j["json"] = json.toJson();
    }
    return j;
  }
}

/// {@tool json2dart --name AccountSummaryJson}
/// * j: `1`
/// * d: `"a"`
/// {@end-tool}
class AccountSummaryJson {
  num j;
  String d;

  AccountSummaryJson({
    this.j,
    this.d,
  });

  AccountSummaryJson.fromJson(Map<String, dynamic> json) {
    j = json["j"] as num;
    d = json["d"] as String;
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    json["j"] = j;
    json["d"] = d;
    return json;
  }
}

/// {@tool json2dart --name AccMonthItem}
/// * blance: `38.9`
/// {@end-tool}
class AccMonthItem {
  num blance;

  AccMonthItem({
    this.blance,
  });

  AccMonthItem.fromJson(Map<String, dynamic> json) {
    blance = json["blance"] as num;
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    json["blance"] = blance;
    return json;
  }
}
