// GENERATED BY `json2dart --name Test --yes --from test.json`

/// {@tool json2dart --name Test}
/// * count: `1`
/// * items: `<TestItem>[]`
/// {@end-tool}
class Test {
  num count;
  List<TestItem> items;

  Test({
    this.count,
    this.items,
  });

  Test.fromJson(Map<String, dynamic> json) {
    count = json["count"] as num;
    items = (json["items"] as List)?.map((v) => TestItem.fromJson(v))?.toList();
  }

  Map<String, dynamic> toJson() {
    final _map = <String, dynamic>{};
    _map["count"] = count;
    if (items != null) {
      _map["items"] = items.map((v) => v.toJson()).toList();
    }
    return _map;
  }
}

/// {@tool json2dart --name TestItem}
/// * id: `1`
/// * name: `"name"`
/// {@end-tool}
class TestItem {
  num id;
  String name;

  TestItem({
    this.id,
    this.name,
  });

  TestItem.fromJson(Map<String, dynamic> json) {
    id = json["id"] as num;
    name = json["name"] as String;
  }

  Map<String, dynamic> toJson() {
    final _map = <String, dynamic>{};
    _map["id"] = id;
    _map["name"] = name;
    return _map;
  }
}
